### ISSUE TITLE
Expected class name but found property. (-2741)

### ISSUE THREAD

**Issue by wookayin** [junegunn/vim-xmark#8]
Every time `:Xmark` is typed or on save (`:w`), I have the following error:

```
Failed to reload the page: 371:374: syntax error: Expected class name but found property. (-2741)
```

Perhaps it is an applescript error, but I didn't figure out why.

Some Environments:

- Mac OS X 10.10.5
- iTerm2 Nightly
- 44.0.2403.157 (64-bit)

**Comment by junegunn** [comment]
I remember I had the same problem before and I was clueless. However, for some reason unknown, the issue was resolved when I tried again after some time. Maybe I was switching between iterm2 nightly and stable then but I'm not sure.

![have](https://cloud.githubusercontent.com/assets/700826/9609495/dd362634-510e-11e5-82f8-b8acd6080d58.jpg)

Does it also happen with mvim?

**Comment by justinkinney** [comment]
I ran into the same problem. PR submitted.

**Comment by junegunn** [comment]
@justinkinney Thanks. @wookayin Can you check if the suggested fix resolves the issue for you?
